name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # Build api on EC2 instance
  build:
    name: Build
    # Ubuntu instance
    runs-on: ubuntu-latest

    # ssh into instance
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf fast-api-breast-cancer-model
            git clone git@github.com:madt2709/fast-api-breast-cancer-model.git
            cd fast-api-breast-cancer-model
            sudo docker-compose build
            sudo docker-compose up -d
